log4j.rootLogger=DEBUG, estore
log4j.appender.estore=org.apache.log4j.DailyRollingFileAppender
log4j.appender.estore.layout=org.apache.log4j.PatternLayout
log4j.appender.estore.layout.ConversionPattern=[%X{userName}] [%d] %-5p [%c] %m%n
log4j.appender.estore.File=${LOG_DIR}/FordKeyCode.app.log
#log4j.appender.estore.File=C:/fordkeycode/logs/FordKeyCode.app.log

log4j.category.com=DEBUG
log4j.category.com.archway.estore.common.JdbcConnectionFactory=FATAL
log4j.category.com.archway.estore.common.JdbcHelper=FATAL
log4j.category.org.apache=FATAL
log4j.category.org.displaytag=FATAL
#log4j.category.com.archway.estore.filters=FATAL
#log4j.category.com.archway.estore=FATAL



#define extra categories
log4j.category.soapRequestResponse=debug, soapRequestResponse


#set additivity to false so messages do not get added to root category
log4j.additivity.soapRequestResponse=false


#soapRequestResponse
log4j.appender.soapRequestResponse=org.apache.log4j.DailyRollingFileAppender
log4j.appender.soapRequestResponse.File=${LOG_DIR}/soapRequestResponse.app.log
log4j.appender.soapRequestResponse.layout=org.apache.log4j.PatternLayout
log4j.appender.soapRequestResponse.layout.ConversionPattern=[%d] [location - %c] - %m%n