package com.archway.estore.servlet;

import com.archway.estore.common.Logger;
import com.archway.webservices.VinImplHelper;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * 
 * Archway Marketing Services.
 * 7525 Cogswell Rd,
 * Romulus, MI - 48174.
 * Phone - 734.713.2000
 * 
 * Project Name            : FordKeyCode
 * 
 * Author                  : bhattam0 - Amar Bhatt Email:(AMAR_BHATT@ARCHWAY.COM) PH. 734.713.2019
 * File Name               : KeyCodeServlet.java 
 * Package Name            : com.archway.estore.servlet
 * 
 * Date                    : Jan 20, 2014 9:02:18 PM
 * 
 * Change Date             : Jan 20, 2014 9:02:18 PM
 * 							 
 * ---------------------------------------------------------
 * Description :- Add Class Description here
 * ---------------------------------------------------------
 * 
 * http://autoweb.tsdet.archway.com/keycode/servlet/KeyCodeServlet?key=<key>&pacode=<pacode>&vin=<10
 * characters vin> output :
 * 2000-SUCCESS|99999|1367333021408.796226745.6075553827151558959@Archway-Key-Code-Application.home|1234567890|Y
 * 
 * 
 * http://autoweb.tsdet.archway.com/keycode/servlet/KeyCodeServlet?key=40778b756f90d97ffcff28b81e18de805a70ae4ef4084bd6c9126d0b63332ced&pacode=12345&vin=1234567890
 */

public class KeyCodeServlet extends HttpServlet
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 1L;

	private static Logger		logger				= Logger.getLogger ( KeyCodeServlet.class );

	public void destroy ()
	{
		super.destroy ();
		// TODO Method stub generated by Lomboz
	}

	protected void doGet (
							HttpServletRequest request ,
							HttpServletResponse response )
															throws ServletException ,
															IOException
	{
		// TODO Method stub generated by Lomboz
		String methodName = "KeyCodeServlet ******************************************* ";
		logger.entering ( methodName );

		String key = request.getParameter ( "key" ) != null ? request.getParameter ( "key" ) : "";
		String pacode = request.getParameter ( "pacode" ) != null ? request.getParameter ( "pacode" ) : "";
		String vin = request.getParameter ( "vin" ) != null ? request.getParameter ( "vin" ) : "";

		logger.warn ( "Key    : " + key );
		logger.warn ( "pacode : " + pacode );
		logger.warn ( "vin    : " + vin );

		String html = "";
		String delimiter = "|";
		try
		{
			if ( VinImplHelper.dokeyValidation ( key ) )
			{
				if ( VinImplHelper.doParametersValidation ( vin , pacode ) )
				{

					html = "2000-SUCCESS" + delimiter + pacode + delimiter + VinImplHelper.getPayloadID () + delimiter + vin + delimiter + "Y";

				}
				else
				{
					html = "1010-VIN OR PACODE NOT VALID" + delimiter + pacode + delimiter + VinImplHelper.getPayloadID () + delimiter + vin + delimiter + "N";

				}
			}
			else
			{
				html = "1000-KEY NOT VALID" + delimiter + pacode + delimiter + VinImplHelper.getPayloadID () + delimiter + vin + delimiter + "N";
			}
		}
		catch ( Exception e )
		{
			logger.warn ( "Exception e :" + e.getMessage () );
			html = "9999-FATAL ERROR CONTACT ARCHWAY" + delimiter + pacode + delimiter + VinImplHelper.getPayloadID () + delimiter + vin + delimiter + "N";

		}
		finally
		{
			logger.exiting ( methodName );
			doPost ( request , response , html );
		}

	}

	protected void doPost (
							HttpServletRequest request ,
							HttpServletResponse response ,
							String html ) throws ServletException , IOException
	{
		// TODO Method stub generated by Lomboz

		response.setContentType ( "text/html" );
		PrintWriter out = response.getWriter ();
		try
		{
			// no cache code
			// Set to expire far in the past.
			response.setHeader ( "Expires" , "Sat, 6 May 1995 12:00:00 GMT" );
			// Set standard HTTP/1.1 no-cache headers.
			response.setHeader ( "Cache-Control" , "no-store, no-cache, must-revalidate" );
			// Set IE extended HTTP/1.1 no-cache headers (use addHeader).
			response.addHeader ( "Cache-Control" , "post-check=0, pre-check=0" );
			// Set standard HTTP/1.0 no-cache header.
			response.setHeader ( "Pragma" , "no-cache" );

			response.setContentType ( "text/html" );

			out.println ( html );
		}
		catch ( Exception e )
		{
			logger.warn ( "Exception doPost KeyCodeServlet :" + e.getMessage () );
		}
		out.flush ();
		out.close ();
	}

}
