#log4j.rootLogger=DEBUG, estore
#log4j.appender.estore=org.apache.log4j.DailyRollingFileAppender
#log4j.appender.estore.layout=org.apache.log4j.PatternLayout
#log4j.appender.estore.layout.ConversionPattern=[%X{userName}] [%d] %-5p [%c] %m%n
#log4j.appender.estore.File=D:/logs/FordKeyCode.app.log

log4j.rootLogger=DEBUG, estore
log4j.appender.estore=org.apache.log4j.RollingFileAppender
log4j.appender.estore.layout=org.apache.log4j.PatternLayout
#log4j.appender.estore.layout.ConversionPattern=%d [%t] %-5p (%F:%L) - %m%n
log4j.appender.estore.layout.ConversionPattern=[%X{userName}] [%d] %-5p [%c] %m%n
log4j.appender.estore.File=C:/Logs/FordKeyCode.app.log
log4j.appender.estore.MaxFileSize=5MB
log4j.appender.estore.MaxBackupIndex=200

log4j.category.com=DEBUG
log4j.category.com.archway.estore.common.JdbcConnectionFactory=DEBUG
log4j.category.com.archway.estore.common.JdbcHelper=DEBUG
log4j.category.org.apache=WARN
log4j.category.org.displaytag=WARN
log4j.category.com.archway.estore.filters=DEBUG
log4j.category.com.archway.estore=DEBUG



#define extra categories
log4j.category.soapRequestResponse=debug, soapRequestResponse


#set additivity to false so messages do not get added to root category
log4j.additivity.soapRequestResponse=false


#soapRequestResponse
log4j.appender.soapRequestResponse=org.apache.log4j.DailyRollingFileAppender
log4j.appender.soapRequestResponse.File=C:/Logs/soapRequestResponse.app.log
log4j.appender.soapRequestResponse.layout=org.apache.log4j.PatternLayout
log4j.appender.soapRequestResponse.layout.ConversionPattern=[%d] [location - %c] - %m%n